name: Add New Headline

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Headline Title'
        required: true
      url:
        description: 'Headline URL'
        required: true
      author:
        description: 'Author'
        required: false
        default: 'editor'
      category:
        description: 'Category'
        required: false
        default: 'news'

jobs:
  add-headline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create new headline file
        run: |
          mkdir -p content/headlines
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          FILENAME="content/headlines/headline-${TIMESTAMP}.md"
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "---" > "$FILENAME"
          echo "title: ${{ github.event.inputs.title }}" >> "$FILENAME"
          echo "url: ${{ github.event.inputs.url }}" >> "$FILENAME"
          echo "author: ${{ github.event.inputs.author }}" >> "$FILENAME"
          echo "published: $NOW" >> "$FILENAME"
          echo "updated: $NOW" >> "$FILENAME"
          echo "category: ${{ github.event.inputs.category }}" >> "$FILENAME"
          echo "---" >> "$FILENAME"

          cat "$FILENAME"

      - name: Commit and push headline
        run: |
          git add content/headlines
          git commit -m "Add new headline"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
