backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "headlines"
    label: "Headlines"
    folder: "content/headlines"
    create: true
    slug: "headline-{{timestamp}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "url", label: "URL" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Thumbnail Image", widget: "image" }

  - name: "mainheadline"
    label: "Main Headline"
    files:
      - file: "content/main-headline.md"
        label: "Main Headline"
        name: "mainheadline"
        fields:
          - { name: "title", label: "Title" }
          - { name: "url", label: "URL" }
          - { name: "image", label: "Main Image", widget: "image" }
