collections:
  - name: "headlines"
    label: "Headlines"
    folder: "content/headlines"
    create: true
    slug: "headline-{{timestamp}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "url", label: "URL" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Thumbnail Image", widget: "image" }

  - name: "mainheadline"
    label: "Main Headline"
    folder: "content/mainheadline"
    create: false
    files:
      - file: "content/mainheadline/main.md"
        label: "Main Headline"
        name: "main"
        fields:
          - { name: "title", label: "Title" }
          - { name: "url", label: "URL" }
          - { name: "image", label: "Main Image", widget: "image" }
          - { name: "date", label: "Date", widget: "datetime" }
