backend:
  name: github
  repo: newsnews99/newsnews99.github.io
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "headlines"
    label: "Headlines"
    folder: "content/headlines"
    create: true
    slug: "headline-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "mainheadline"
    label: "Main Headline"
    file: "content/main-headline.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "ticker"
    label: "Ticker Headlines"
    folder: "content/ticker"
    create: true
    slug: "ticker-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }

  - name: "polls"
    label: "Polls"
    folder: "content/polls"
    create: true
    slug: "poll-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Options", name: "options", widget: "list" }
