backend:
  name: git-gateway
  branch: main

media_folder: "data"
public_folder: "/data"

collections:
  - name: "headlines"
    label: "Headlines"
    folder: "content/headlines"
    create: true
    slug: "headline-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "editor" }
      - { label: "Published", name: "published", widget: "datetime" }
      - { label: "Updated", name: "updated", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string", default: "news" }
