name: Add New Headline

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Headline Title'
        required: true
      url:
        description: 'Headline URL'
        required: true

jobs:
  add-headline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create headline file
        run: |
          mkdir -p content/headlines
          FILE_PATH="content/headlines/${{ github.run_id }}.md"
          echo "---" > $FILE_PATH
          echo "title: ${{ github.event.inputs.title }}" >> $FILE_PATH
          echo "url: ${{ github.event.inputs.url }}" >> $FILE_PATH
          echo "---" >> $FILE_PATH
          cat $FILE_PATH

      - name: Commit and push
        run: |
          git add content/headlines/
          git commit -m "Add headline: ${{ github.event.inputs.title }}" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
