name: Add New Headline

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Headline Title'
        required: true
      url:
        description: 'Headline URL'
        required: true

jobs:
  add-headline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # REQUIRED for push access

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create new headline file
        run: |
          mkdir -p content/headlines
          FILENAME="content/headlines/headline-${{ github.run_id }}.md"
          echo "---" > "$FILENAME"
          echo "title: ${{ github.event.inputs.title }}" >> "$FILENAME"
          echo "url: ${{ github.event.inputs.url }}" >> "$FILENAME"
          echo "---" >> "$FILENAME"
          echo "Created file:"
          cat "$FILENAME"

      - name: Commit and push
        run: |
          git add content/headlines/
          git status
          git commit -m "Add headline: ${{ github.event.inputs.title }}" || echo "Nothing to commit"
          git push origin HEAD:main
