name: Add New Headline

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Headline Title'
        required: true
      url:
        description: 'Headline URL'
        required: true

jobs:
  add-headline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create headline file
        run: |
          mkdir -p content/headlines
          TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
          FILENAME="content/headlines/headline-${TIMESTAMP}.md"
          echo "---" > "$FILENAME"
          echo "title: ${{ github.event.inputs.title }}" >> "$FILENAME"
          echo "url: ${{ github.event.inputs.url }}" >> "$FILENAME"
          echo "author: ${{ github.actor }}" >> "$FILENAME"
          echo "published: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$FILENAME"
          echo "updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$FILENAME"
          echo "category: news" >> "$FILENAME"
          echo "---" >> "$FILENAME"
          cat "$FILENAME"

      - name: Commit and push file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add content/headlines/
          git commit -m "Add headline: ${{ github.event.inputs.title }}" || echo "Nothing to commit"
          git push origin HEAD:main
