name: Generate RSS Feed

on:
  push:
    paths:
      - 'data/headlines.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install xmlbuilder

      - name: Generate RSS feed
        run: node generate-rss.js

      - name: Commit RSS feed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feed.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
