name: Generate Headlines JSON

on:
  push:
    paths:
      - "content/headlines/**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install gray-matter

      - name: Convert Markdown to JSON
        run: |
          mkdir -p public
          node <<EOF
          const fs = require('fs');
          const matter = require('gray-matter');

          const dir = 'content/headlines';
          const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));

          const headlines = files.map(file => {
            const content = fs.readFileSync(\`\${dir}/\${file}\`, 'utf8');
            const { data } = matter(content);
            return {
              title: data.title || '',
              url: data.url || '',
              image: data.image || '',
              author: data.author || '',
              category: data.category || '',
              published: data.published || '',
              updated: data.updated || ''
            };
          });

          fs.writeFileSync('public/headlines.json', JSON.stringify(headlines, null, 2));
          EOF

      - name: Commit JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/headlines.json
          git commit -m "Update headlines.json" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
