name: Generate Headlines JSON

on:
  push:
    branches:
      - main
    paths:
      - 'content/headlines/**'
      - 'content/mainheadline/**'

jobs:
  build-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install gray-matter
        run: npm install gray-matter

      - name: Generate JSON
        run: |
          node <<EOF
          const fs = require('fs');
          const matter = require('gray-matter');
          const headlines = [];

          // Process headlines
          fs.readdirSync('content/headlines').forEach(file => {
            if (file.endsWith('.md')) {
              const content = fs.readFileSync(\`content/headlines/\${file}\`, 'utf8');
              const data = matter(content).data;
              headlines.push(data);
            }
          });

          headlines.sort((a,b) => new Date(b.date) - new Date(a.date));

          const latest = headlines.slice(0, 40);
          const archive = headlines.slice(40);

          fs.writeFileSync('data/headlines.json', JSON.stringify(latest, null, 2));
          fs.writeFileSync('data/archive.json', JSON.stringify(archive, null, 2));

          // Process main headline
          const mainContent = fs.readFileSync('content/mainheadline/main.md', 'utf8');
          const mainData = matter(mainContent).data;
          fs.writeFileSync('data/main-headline.json', JSON.stringify(mainData, null, 2));
          EOF

      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*.json
          git commit -m "Update headlines JSON"
          git push
