name: Generate Headlines JSON

on:
  push:
    paths:
      - "content/headlines/**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install gray-matter

      - name: Create JSON generator script
        run: |
          echo "const fs = require('fs');" > generate.js
          echo "const matter = require('gray-matter');" >> generate.js
          echo "const dir = 'content/headlines';" >> generate.js
          echo "const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));" >> generate.js
          echo "const headlines = files.map(file => {" >> generate.js
          echo "  const content = fs.readFileSync(\`\${dir}/\${file}\`, 'utf8');" >> generate.js
          echo "  const { data } = matter(content);" >> generate.js
          echo "  return {" >> generate.js
          echo "    title: data.title || ''," >> generate.js
          echo "    url: data.url || ''," >> generate.js
          echo "    image: data.image || ''," >> generate.js
          echo "    author: data.author || ''," >> generate.js
          echo "    category: data.category || ''," >> generate.js
          echo "    published: data.published || ''," >> generate.js
          echo "    updated: data.updated || ''" >> generate.js
          echo "  };" >> generate.js
          echo "});" >> generate.js
          echo "fs.writeFileSync('headlines.json', JSON.stringify(headlines, null, 2));" >> generate.js

      - name: Run JSON generator
        run: node generate.js

      - name: Commit JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add headlines.json
          git commit -m "Update headlines.json" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
